base_config:
- config/logging.yaml
- config/wandb.yaml
- config/finetune_gsfixer/replica_train.yaml
- config/finetune_gsfixer/replica_val.yaml
- config/finetune_gsfixer/replica_vis.yaml
- config/model_gsfixer.yaml

pipeline:
  name: MarigoldGSFixerPipeline
  kwargs:
    default_denoising_steps: 4
    default_processing_resolution: 768

dataloader:
  num_workers: 2
  effective_batch_size: 32
  max_train_batch_size: 2
  seed: 2025  # to ensure continuity when resuming from checkpoint

trainer:
  name: MarigoldGSFixerFinetune
  init_seed: 2025  # use null to train w/o seeding
  save_period: 400
  backup_period: 1000
  validation_period: 400
  visualization_period: 100

multi_res_noise:
  strength: 0.9
  annealed: true
  downscale_strategy: original

max_epoch: 10000  # a large enough number
max_iter: 800

optimizer:
  name: Adam

loss:
  name: mse_loss
  kwargs:
    reduction: mean

lr: 3.0e-05
lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 25000
    final_ratio: 0.01
    warmup_steps: 100

# Light setting for the in-training validation and visualization
validation:
  denoising_steps: 1
  ensemble_size: 1
  processing_res: 0
  match_input_res: false
  resample_method: bilinear
  main_val_metric: lpips
  main_val_metric_goal: minimize
  init_seed: 2025

eval:
  alignment: least_square
  align_max_res: null
  eval_metrics:
  - mse
  - psnr
  - ssim
  - lpips